#+OPTIONS: toc:nil

# Tags seperated by commas and spaces
#+BEGIN_SRC markdown
Title: Road Trip 2018: Departure
Date: 2018-07-23T23:24:40
Tags: rt18, travel, DRAFT
#+END_SRC

#+ll-process: (ll-replace "^\\* " "<br></br><br></br>\n* ")

* Header :notitle:
Getting ready to leave.
#+HTML: <!-- more -->

* Content :notitle:

* The Plan
My friends and I are driving across America for +six+ five weeks.
Road trips play some sort of central role in American culture, and we wanted to have the experience and see our own country.

We decided to buy an RV because we discovered how cheap they are.
Browsing Craigslist and RVShare, we saw dozens of RVs for sale around $5-10k.
Not only was this an affordable up-front cost for a six-week vacation, we reasoned that we can even recoup the cost if we can resell it after the trip.

Our RV was found on Craigslist for just $5k.
While a little beat up, its engine ran nicely and its fundamental systems seemed fully operational.
However, the previous owner had it sitting in an empty lot and was generally unwilling to drive it around because it was unregistered and uninsured, so we took his word for some of the systems like the generator, AC, and water pump.
This was probably a mistake.

* Repairing the RV
As we started the repairs we found that a number of these systems didn't work nearly as well as we might have hoped.
The right hand mirror was mounted on such flimsy wood that it shook too much to be useful, the heating did not seem to work, the gas gauge was broken, and so on...
While we resolved those relatively easily, the remaining large issue was that the generator failed to produce any power.

Indeed, the generator has proven to be the single largest issue, despite seeming like a simple fix at the start;
our struggle to fix it ultimately delayed the trip by over a week.
Contrary to what we had been told when we bought the RV, the generator turned out to run on propane (not diesel), and few mechanics seem to work on propane RV generators.
In fact, we couldn't find a single mechanic who would even look at the generator, though they only told us after keeping the RV in the shop for a several days.

We're getting the RV back today and are going to leave as soon as we get it.
Given that we are now a week late, we decided to try a few quick fixes for the generator and then depart regardless of whether they work.
Being without a generator will mean no AC while on the road, but that's better than not being on the road at all.


* Pre-departure Costs
Repairing the RV cost significantly more money than we expected; we expected two or three thousand dollars of repairs but ended up with about five thousand.

I've itemized out costs below, identifying the major categories of the expenses. Minor expenses or pieces particular to the issues with our RV have been aggregated in "Misc repairs".
| Item                               | Cost ($) |
|------------------------------------+----------|
| RV                                 |     5000 |
| Repairs                            |          |
| - New Tires                        |  1896.55 |
| - Fluid changes, tune-ups          |   474.14 |
| - Misc repairs                     |  1578.18 |
| Misc Supplies                      |          |
| - National parks pass              |      165 |
| - Bike rack                        |   105.19 |
| - Insurance payments               |   502.40 |
| - Mobile hotspot                   |       80 |
|------------------------------------+----------|
| *Total* pre-departure costs          |  9721.46 |
#+TBLFM: @12$2=vsum(@2..@-2)
